### ISSUE TITLE
Add Setting for pages to reload each time

### ISSUE THREAD

**Issue by Rafkev** [majick777/teleporter#7] opened 2023-02-25 19:33 UTC
Hello Majick, once teleporter is activated the menu bar becomes unclickable. Any reason for this? Can this be checked please

**Comment by majick777** [comment] 2023-02-26 12:19
Hi @Rafkev thanks for reporting.

I'm checking and I can't seem to reproduce the problem yet. The plugin has from the start attempted to always ignore any admin bar links, and any links with `/wp-admin/` in them for that matter.

I did see in my code that there is a potential problem, as it applies the first ignore class on the admin bar links, but if there are no ignore classes set (ie. they have been cleared from the plugin settings) then this might cause a conflict (though it still didn't make any links unclickable for me.) 

So I updated the development version and set an ignore attribute on those links instead. This may or may not fix your problem, but if you can test it and report back with the result:
https://github.com/majick777/teleporter/tree/develop/

**Comment by Rafkev** [comment] 2023-02-26 14:56
Thank you for your response Majick, I have recorded my screen, please find the attached video, sent via email so you can see. I installed the updated as you suggested but still the same issue. 
Thank you

**Comment by majick777** [comment] 2023-03-01 07:44
@Rafkev I didn't receive an email, so I'm not sure where you sent it, can you post the recording link URL perhaps?

**Comment by Rafkev** [comment] 2023-03-01 07:54
Sure, here it is. https://www.transfernow.net/dl/202303019yaeCesv/AvUSQ2Gi

Please I will appreciate if tabs, buttons will work when the plugin is
activated.

**Comment by majick777** [comment] 2023-03-01 08:09
@Rafkev Thanks for this, I did think you were meaning backend admin menu rather than frontend site menu links. 

Okay so the plugin does try it's best to detect links on the page automatically. However sometimes it requires some manual configuration (as per the readme) for links to ignore, and also dynamically created links.

For example, you may want to ignore a cart link completely because you want to make sure the latest refreshed copy of the cart contents are loaded. Or if it is interfering with the search button click you may want to ignore that also.

For the menus, some mobile menu scripts/blocks/modules/widgets add links to the page dynamically, so that only when they are clicked do the links exist. We had this issue come up recently in a build so I came up with a way to solve this. All you need to do is find the common class name for the dynamic links (inspect the links when the menu is open to find this) and add that to the settings. (On the recent build for example we ended up with needing to add for this setting: `mobile-link,jet-breadcrumbs__item-link,elementor-item` - this was a site with Jet mobile menu and breadcrumbs and Elementor page builder.)

**Comment by Rafkev** [comment] 2023-03-01 08:18
Thank you so kindly for your prompt response. I will check it out and
update you.

**Comment by Rafkev** [comment] 2023-03-06 12:38
Hello Majick,

Please is it possible to add a section on your plugin where users select
pages that they don't want the plugin feature to apply on?

For example: If I don't want a feature to apply to the cart page, I can
select or add cart age to the Don't apply feature section.

I hope to hear from you soon.

Thank you.

**Comment by majick777** [comment] 2023-03-14 05:37
@Rafkev That's a very good idea! Okay, I'll see what I can do...

**Comment by Rafkev** [comment] 2023-03-14 06:39
Awesome, thanks! Please how soon can you help with this?

**Comment by majick777** [comment] 2023-03-14 07:18
@Rafdev It's a fairly quick thing really so I've written a quick patch for this already. But out of time right now, so will have to test it out  myself later today before I can push it to development branch.

**Comment by majick777** [comment] 2023-03-15 12:30
@Rafkev Okay, a little bit tricker that I thought, but seems to work after more testing/tweaking.
Try it out yourself and let me know how it goes:
https://github.com/majick777/teleporter/tree/develop

**Comment by Rafkev** [comment] 2023-03-15 13:39
Oh! Thank you so much. I will test and feed you back.

**Comment by Rafkev** [comment] 2023-03-22 08:52
Hi team,

It works well but things like chat icons get duplicated when one revisit
pages. Can we work around leverage browser cache?
This will help the excluded pages maintain the same speed on the overall
website.

Thank you.

**Comment by majick777** [comment] 2023-03-27 07:22
@Rafkev Can you give me an example of "chat icons being duplicated" on a page? Without being able to inspect what is happening I'm going to be just guessing. The plugin can't account for all possible script embeds, especially chat widgets which tend to be externally embedded scripts, so this might be out of scope.

That said, it's also possible that you could add your own event listener to a Teleporter custom event to hide/show the chat icons on the originally loaded page when switching away/to it. I'm guessing they might be showing because the icon has a fixed or absolute position in the original window. But for that to happen I'd think they'd need to be somehow "outside" the body tag... otherwise they should be hidden/display just like the other page elements.

**Comment by majick777** [comment] 2023-03-31 04:17
@Rafkev I'm going to close this issue as done and include it in the next release. If you want to continue to explore the chat widget behavior, please open a new issue and provide some more specific details regarding that problem.

**Closed as completed by majick777** 2023-03-31 04:17 UTC
Labels: enhancement
